<template>
  <div>
    <div class="item-list">
      <PropItem
        v-for="um in ultramedal"
        v-bind:item="um"
        :urlType="1"
        :key="um.id"
      />
    </div>
  </div>
</template>

<script>
import PropItem from "@/components/PropItem";
export default {
  name: "UltraMedal",
  components: {
    PropItem,
  },
  data() {
    return {
      ultramedal: [
        {
          id: "U-001", //唯一ID
          type: "U", //U 奥特曼  M 怪兽  O 其它
          tag: ["DX"], //标签：限定 DX EX扩展 SG食玩 GP扭蛋 SP特殊 PF披风
          name: "赛罗奥特曼", //名称
          tag: [62], //关联奥特曼或怪兽实体数组
        },
        {
          id: "U-002",
          type: "U",
          tag: ["DX"],
          name: "赛文奥特曼",
          tag: [2],
        },
        {
          id: "U-003",
          type: "U",
          tag: ["DX"],
          name: "雷欧奥特曼",
          tag: [8],
        },
        {
          id: "U-004",
          type: "U",
          tag: ["DX"],
          name: "奥特曼",
          tag: [0],
        },
        {
          id: "U-005",
          type: "U",
          tag: ["DX"],
          name: "艾斯奥特曼",
          tag: [4],
        },
        {
          id: "U-006",
          type: "U",
          tag: ["DX"],
          name: "泰罗奥特曼",
          tag: [6],
        },
        {
          id: "U-007",
          type: "U",
          tag: ["DX"],
          name: "迪迦奥特曼",
          tag: [20],
        },
        {
          id: "U-008",
          type: "U",
          tag: ["DX"],
          name: "戴拿奥特曼",
          tag: [27],
        },
        {
          id: "U-009",
          type: "U",
          tag: ["DX"],
          name: "盖亚奥特曼",
          tag: [30],
        },
        {
          id: "U-010",
          type: "U",
          tag: ["DX"],
          name: "赛罗奥特曼 无限形态",
          tag: [88],
        },
        {
          id: "U-011",
          type: "U",
          tag: ["DX"],
          name: "捷德奥特曼",
          tag: [103],
        },
        {
          id: "U-012",
          type: "U",
          tag: ["DX"],
          name: "极恶 贝利亚",
          tag: [123],
        },
        {
          id: "U-013",
          type: "U",
          tag: ["DX"],
          name: "佐菲",
          tag: [1],
        },
        {
          id: "U-014",
          type: "U",
          tag: ["DX"],
          name: "杰克奥特曼",
          tag: [3],
        },
        {
          id: "U-015",
          type: "U",
          tag: ["DX"],
          name: "奥特之父",
          tag: [5],
        },
        {
          id: "U-016",
          type: "U",
          tag: ["DX"],
          name: "高斯奥特曼",
          tag: [38],
        },
        {
          id: "U-017",
          type: "U",
          tag: ["DX"],
          name: "奈克赛斯奥特曼",
          tag: [46],
        },
        {
          id: "U-018",
          type: "U",
          tag: ["DX"],
          name: "梦比优斯奥特曼",
          tag: [54],
        },
        {
          id: "U-019",
          type: "U",
          tag: ["DX"],
          name: "银河奥特曼",
          tag: [65],
        },
        {
          id: "U-020",
          type: "U",
          tag: ["DX"],
          name: "艾克斯奥特曼",
          tag: [67],
        },
        {
          id: "U-021",
          type: "U",
          tag: ["DX"],
          name: "欧布奥特曼",
          tag: [68],
        },
        {
          id: "U-022",
          type: "U",
          tag: ["EX"],
          name: "赛罗奥特曼 闪耀形态",
          tag: [64],
        },
        {
          id: "U-023",
          type: "U",
          tag: ["EX"],
          name: "火焰骑士",
          tag: null,
        },
        {
          id: "U-024",
          type: "U",
          tag: ["EX"],
          name: "镜子骑士",
          tag: null,
        },
        {
          id: "U-025",
          type: "U",
          tag: ["EX"],
          name: "钢铁九号",
          tag: null,
        },
        {
          id: "U-026",
          type: "U",
          tag: ["EX"],
          name: "钢铁杀手",
          tag: null,
        },
        {
          id: "U-027",
          type: "U",
          tag: ["EX"],
          name: "捷德奥特曼",
          tag: [103],
        },
        {
          id: "U-028",
          type: "U",
          tag: ["EX"],
          name: "银河斯特利姆奥特曼",
          tag: [90],
        },
        {
          id: "U-029",
          type: "U",
          tag: ["EX"],
          name: "维克特利奥特曼 骑士形态",
          tag: [91],
        },
        {
          id: "U-030",
          type: "U",
          tag: ["EX"],
          name: "超越艾克斯",
          tag: [93],
        },
        {
          id: "U-031",
          type: "U",
          tag: ["EX"],
          name: "捷德奥特曼 尊皇形态",
          tag: [107],
        },
        {
          id: "U-032",
          type: "U",
          tag: ["EX"],
          name: "罗布奥特曼",
          tag: [116],
        },
        {
          id: "U-033",
          type: "U",
          tag: ["EX"],
          name: "泰迦三重斯特利姆",
          tag: [118],
        },
        {
          id: "U-034",
          type: "U",
          tag: ["EX"],
          name: "银河维克特利奥特曼",
          tag: [92],
        },
        {
          id: "U-035",
          type: "U",
          tag: ["EX"],
          name: "艾克斯奥特曼 贝塔火花装甲",
          tag: [94],
        },
        {
          id: "U-036",
          type: "U",
          tag: ["EX"],
          name: "欧布奥特曼 三重形态",
          tag: [102],
        },
        {
          id: "U-037",
          type: "U",
          tag: ["EX"],
          name: "捷德奥特曼 终极形态",
          tag: [108],
        },
        {
          id: "U-038",
          type: "U",
          tag: ["EX"],
          name: "格罗布奥特曼",
          tag: [117],
        },
        {
          id: "U-039",
          type: "U",
          tag: ["EX"],
          name: "令迦奥特曼",
          tag: [124],
        },
        {
          id: "U-040",
          type: "U",
          tag: ["EX"],
          name: "奥特六兄弟",
          tag: [0, 1, 2, 3, 4, 6],
        },
        {
          id: "U-041",
          type: "U",
          tag: ["EX"],
          name: "爱迪奥特曼",
          tag: [12],
        },
        {
          id: "U-042",
          type: "U",
          tag: ["EX"],
          name: "杰斯提斯奥特曼 标准模式",
          tag: [43],
        },
        {
          id: "U-043",
          type: "U",
          tag: ["EX"],
          name: "希卡利奥特曼",
          tag: [58],
        },
        {
          id: "U-044",
          type: "U",
          tag: ["EX"],
          name: "赛罗奥特曼 月神奇迹型",
          tag: [87],
        },
        {
          id: "U-045",
          type: "U",
          tag: ["EX"],
          name: "利布特奥特曼",
          tag: [125],
        },
        {
          id: "U-046",
          type: "U",
          tag: ["GP"],
          name: "赛文奥特曼 闪耀型",
          tag: [2],
        },
        {
          id: "U-047",
          type: "U",
          tag: ["GP"],
          name: "奥特曼 闪耀型",
          tag: [0],
        },
        {
          id: "U-048",
          type: "U",
          tag: ["GP"],
          name: "葛雷奥特曼",
          tag: [17],
        },
        {
          id: "U-049",
          type: "U",
          tag: ["GP"],
          name: "赛罗奥特曼 强壮日冕型",
          tag: [86],
        },
        {
          id: "U-050",
          type: "U",
          tag: ["GP"],
          name: "阿古茹奥特曼",
          tag: [33],
        },
        {
          id: "U-051",
          type: "U",
          tag: ["GP"],
          name: "乔尼亚斯奥特曼",
          tag: [11],
        },
        {
          id: "U-052",
          type: "M",
          tag: ["GP"],
          name: "内隆嘎",
          tag: null,
        },
        {
          id: "U-053",
          type: "M",
          tag: ["GP"],
          name: "盖内伽古",
          tag: null,
        },
        {
          id: "U-054",
          type: "M",
          tag: ["GP"],
          name: "吉拉斯",
          tag: null,
        },
        {
          id: "U-055",
          type: "U",
          tag: ["GP"],
          name: "奈克斯特奥特曼 蓝色青年形态",
          tag: [50],
        },
        {
          id: "U-056",
          type: "U",
          tag: ["GP"],
          name: "戴拿奥特曼 奇迹型",
          tag: [29],
        },
        {
          id: "U-056",
          type: "U",
          tag: ["GP"],
          name: "戴拿奥特曼",
          tag: [29],
        },
        {
          id: "U-057",
          type: "U",
          tag: ["GP"],
          name: "闪耀迪迦",
          tag: [23],
        },
        {
          id: "U-058",
          type: "U",
          tag: ["GP"],
          name: "帕瓦特奥特曼",
          tag: [18],
        },
        {
          id: "U-059",
          type: "U",
          tag: ["GP"],
          name: "奥特之王",
          tag: [10],
        },
        {
          id: "U-060",
          type: "M",
          tag: ["GP"],
          name: "伽古拉斯·伽古拉",
          tag: null,
        },
        {
          id: "U-061",
          type: "M",
          tag: ["GP"],
          name: "金古桥",
          tag: null,
        },
        {
          id: "U-062",
          type: "U",
          tag: ["GP"],
          name: "哉阿斯奥特曼",
          tag: [19],
        },
        {
          id: "U-063",
          type: "U",
          tag: ["GP"],
          name: "纳伊斯奥特曼",
          tag: [35],
        },
        {
          id: "U-064",
          type: "U",
          tag: ["GP"],
          name: "格丽乔奥特曼",
          tag: [74],
        },
        {
          id: "U-065",
          type: "M",
          tag: ["GP"],
          name: "特空机1号 赛文加",
          tag: null,
        },
        {
          id: "U-066",
          type: "M",
          tag: ["GP"],
          name: "特空机2号 乌英达姆",
          tag: null,
        },
        {
          id: "U-067",
          type: "M",
          tag: ["GP"],
          name: "特空机3号 金古桥军械库定制",
          tag: null,
        },
        {
          id: "U-068",
          type: "M",
          tag: ["GP"],
          name: "特空机4号 奥特人造机甲赛罗",
          tag: null,
        },
        {
          id: "U-069",
          type: "M",
          tag: ["GP"],
          name: "歼灭机甲兽德斯特鲁多斯",
          tag: null,
        },
        {
          id: "U-070",
          type: "M",
          tag: ["GP"],
          name: "虚空怪兽格利扎",
          tag: null,
        },
        {
          id: "U-071",
          type: "U",
          tag: ["SG"],
          name: "究极赛罗",
          tag: [74],
        },
        {
          id: "U-072",
          type: "U",
          tag: ["SG"],
          name: "欧布奥特曼 重光形态",
          tag: [96],
        },
        {
          id: "U-073",
          type: "U",
          tag: ["SG"],
          name: "维克特利奥特曼",
          tag: [66],
        },
        {
          id: "U-074",
          type: "U",
          tag: ["SG"],
          name: "麦克斯奥特曼",
          tag: [52],
        },
        {
          id: "U-075",
          type: "U",
          tag: ["SG"],
          name: "泰迦奥特曼",
          tag: [77],
        },
        {
          id: "U-076",
          type: "U",
          tag: ["SG"],
          name: "泰塔斯奥特曼",
          tag: [79],
        },
        {
          id: "U-077",
          type: "U",
          tag: ["SG"],
          name: "风马奥特曼",
          tag: [80],
        },
        {
          id: "U-078",
          type: "U",
          tag: ["SG"],
          name: "奈克斯特奥特曼青年形态",
          tag: [49],
        },
        {
          id: "U-079",
          type: "M",
          tag: ["SG"],
          name: "艾雷王",
          tag: null,
        },
        {
          id: "U-080",
          type: "M",
          tag: ["SG"],
          name: "艾斯杀手",
          tag: null,
        },
        {
          id: "U-081",
          type: "M",
          tag: ["SG"],
          name: "霍洛波罗兹",
          tag: null,
        },
        {
          id: "U-082",
          type: "M",
          tag: ["SG"],
          name: "吉尔巴里斯",
          tag: null,
        },
        {
          id: "U-083",
          type: "M",
          tag: ["SG"],
          name: "加拉特隆MK2",
          tag: null,
        },
        {
          id: "U-084",
          type: "U",
          tag: ["限定"],
          name: "赛罗与捷德",
          tag: [62, 103],
        },
        {
          id: "U-085",
          type: "U",
          tag: ["限定"],
          name: "戴拿奥特曼 强壮型",
          tag: [28],
        },
        {
          id: "U-086",
          type: "U",
          tag: ["限定"],
          name: "高斯奥特曼 日冕模式",
          tag: [39],
        },
        {
          id: "U-087",
          type: "U",
          tag: ["限定"],
          name: "初代光线",
          tag: [0],
        },
        {
          id: "U-088",
          type: "U",
          tag: ["限定"],
          name: "泽塔奥特曼 阿尔法装甲",
          tag: [81, 62, 2, 8],
        },
        {
          id: "U-089",
          type: "U",
          tag: ["限定"],
          name: "泽塔奥特曼 伽马未来",
          tag: [81, 20, 27, 30],
        },
        {
          id: "U-090",
          type: "U",
          tag: ["限定"],
          name: "泽塔奥特曼 德尔塔天爪",
          tag: [81, 71, 88, 123],
        },
        {
          id: "U-091",
          type: "U",
          tag: ["限定"],
          name: "十周年赛罗",
          tag: [62],
        },
        {
          id: "U-092",
          type: "U",
          tag: ["限定"],
          name: "泽塔奥特曼 德尔塔天爪圣诞版",
          tag: [122],
        },
        {
          id: "U-093",
          type: "U",
          tag: ["限定"],
          name: "罗索奥特曼",
          tag: [72],
        },
        {
          id: "U-093",
          type: "U",
          tag: ["限定"],
          name: "布鲁奥特曼",
          tag: [73],
        },
        {
          id: "U-094",
          type: "U",
          tag: ["SP"],
          name: "泽塔奥特曼",
          tag: [73],
        },
        {
          id: "U-095",
          type: "U",
          tag: ["SP"],
          name: "银河奥特曼",
          tag: [73],
        },
        {
          id: "U-096",
          type: "U",
          tag: ["SP"],
          name: "维克特利奥特曼",
          tag: [73],
        },
        {
          id: "U-097",
          type: "U",
          tag: ["SP"],
          name: "艾克斯奥特曼",
          tag: [73],
        },
        {
          id: "U-098",
          type: "U",
          tag: ["SP"],
          name: "欧布奥特曼",
          tag: [73],
        },
        {
          id: "U-099",
          type: "U",
          tag: ["SP"],
          name: "捷德奥特曼",
          tag: [73],
        },
        {
          id: "U-100",
          type: "U",
          tag: ["SP"],
          name: "罗索奥特曼",
          tag: [73],
        },
        {
          id: "U-101",
          type: "U",
          tag: ["SP"],
          name: "布鲁奥特曼",
          tag: [73],
        },
        {
          id: "U-102",
          type: "U",
          tag: ["SP"],
          name: "泰迦奥特曼",
          tag: [73],
        },
        {
          id: "U-103",
          type: "U",
          tag: ["PF"],
          name: "赛罗奥特曼",
          tag: [73],
        },
        {
          id: "U-104",
          type: "U",
          tag: ["PF"],
          name: "奥特曼",
          tag: [73],
        },
        {
          id: "U-105",
          type: "U",
          tag: ["PF"],
          name: "佐菲奥特曼",
          tag: [73],
        },
        {
          id: "U-106",
          type: "U",
          tag: ["PF"],
          name: "赛文奥特曼",
          tag: [73],
        },
        {
          id: "U-107",
          type: "U",
          tag: ["PF"],
          name: "杰克奥特曼",
          tag: [73],
        },
        {
          id: "U-108",
          type: "U",
          tag: ["PF"],
          name: "艾斯奥特曼",
          tag: [73],
        },
        {
          id: "U-109",
          type: "U",
          tag: ["PF"],
          name: "泰罗奥特曼",
          tag: [73],
        },
        {
          id: "U-110",
          type: "U",
          tag: ["GP"],
          name: "奥特之母",
          tag: [73],
        },
        {
          id: "U-111",
          type: "U",
          tag: ["GP"],
          name: "尤莉安",
          tag: [73],
        },
        {
          id: "U-112",
          type: "U",
          tag: ["GP"],
          name: "索拉",
          tag: [73],
        },
        {
          id: "U-113",
          type: "U",
          tag: ["GP"],
          name: "博伊",
          tag: [73],
        },
        {
          id: "U-114",
          type: "U",
          tag: ["GP"],
          name: "察克",
          tag: [73],
        },
        {
          id: "U-115",
          type: "U",
          tag: ["GP"],
          name: "史考特",
          tag: [73],
        },
        {
          id: "U-116",
          type: "U",
          tag: ["GP"],
          name: "贝斯",
          tag: [73],
        },
        {
          id: "U-117",
          type: "U",
          tag: ["GP"],
          name: "杰诺",
          tag: [73],
        },
        {
          id: "U-118",
          type: "U",
          tag: ["GP"],
          name: "赛文21",
          tag: [73],
        },
        {
          id: "U-119",
          type: "U",
          tag: ["GP"],
          name: "奈欧斯",
          tag: [73],
        },
        {
          id: "U-120",
          type: "U",
          tag: ["GP"],
          name: "奈克斯特",
          tag: [73],
        },
        {
          id: "U-121",
          type: "U",
          tag: ["GP"],
          name: "诺亚",
          tag: [73],
        },
        {
          id: "U-122",
          type: "U",
          tag: ["PB"],
          name: "泽塔奥特曼 阿尔法装甲",
          tag: [73],
        },
        {
          id: "U-123",
          type: "U",
          tag: ["PB"],
          name: "泽塔奥特曼 贝塔冲击",
          tag: [73],
        },
        {
          id: "U-124",
          type: "U",
          tag: ["PB"],
          name: "泽塔奥特曼 伽马未来",
          tag: [73],
        },
        {
          id: "U-125",
          type: "U",
          tag: ["PB"],
          name: "泽塔奥特曼 德尔塔天爪",
          tag: [73],
        },
        {
          id: "U-126",
          type: "O",
          tag: ["PB"],
          name: "武器1",
          tag: [73],
        },
        {
          id: "U-127",
          type: "O",
          tag: ["PB"],
          name: "武器2",
          tag: [73],
        },
        {
          id: "U-128",
          type: "O",
          tag: ["PB"],
          name: "武器3",
          tag: [73],
        },
        {
          id: "U-129",
          type: "M",
          tag: ["PB"],
          name: "杰顿",
          tag: null,
        },
        {
          id: "U-130",
          type: "M",
          tag: ["PB"],
          name: "庞顿",
          tag: null,
        },
        {
          id: "U-131",
          type: "M",
          tag: ["PB"],
          name: "玛伽大蛇",
          tag: null,
        },
        {
          id: "U-132",
          type: "M",
          tag: ["PB"],
          name: "超古代怪兽 哥尔赞",
          tag: null,
        },
        {
          id: "U-133",
          type: "M",
          tag: ["PB"],
          name: "超古代龙 美尔巴",
          tag: null,
        },
        {
          id: "U-134",
          type: "M",
          tag: ["PB"],
          name: "宇宙海兽 雷丘巴斯",
          tag: null,
        },
        {
          id: "U-135",
          type: "M",
          tag: ["PB"],
          name: "奇兽眼Q",
          tag: null,
        },
        {
          id: "U-136",
          type: "M",
          tag: ["PB"],
          name: "宇宙战斗兽 超戈布",
          tag: null,
        },
        {
          id: "U-137",
          type: "U",
          tag: ["DX"],
          name: "贝利亚奥特曼",
          tag: [60],
        },
        {
          id: "U-138",
          type: "M",
          tag: ["DX"],
          name: "宇古代怪兽 哥莫拉",
          tag: null,
        },
        {
          id: "U-139",
          type: "M",
          tag: ["DX"],
          name: "骷髅怪兽 雷德王",
          tag: null,
        }
      ],
    };
  },
  methods: {},
};
</script>

<style scoped>
</style>