<template>
  <div class="item-list" :class="collectStatus ? 'collect-status' : ''">
    <floatLayer
      :show="layerShow"
      :item="nowDetail"
      :urlType="3"
      @parentEvent="hideDetail"
    />
    <div class="ctrl-panel">
      <div
        class="switch-box"
        :class="collectFilter ? 'active' : ''"
        @click="getCollectFilter"
      >
        <div class="switch-label">过滤已拥有的</div>
        <div class="switch-btn"></div>
      </div>
      <div
        class="btn"
        v-text="collectStatus ? '退出标记模式' : '标记我已拥有的'"
        @click="collectToggle"
      ></div>
      <tagBar :tags="tags" @parentEvent="getDataByTag" />
    </div>
    <propItem
      v-for="hk in nowList"
      v-bind:item="hk"
      :class="getCollect(hk.id) ? 'collect' : ''"
      :urlType="3"
      :showPic="true"
      :key="hk.id"
      :defaultColor="'#5420ae'"
      :barColor="hk.color"
      @click.native="showDetail(hk)"
      v-show="collectFilter == false || !getCollect(hk.id)"
    />
  </div>
</template>

<script>
import PropItem from "@/components/PropItem";
import TagBar from "@/components/TagBar";
import FloatLayer from "@/components/FloatLayer";
export default {
  name: "SHF",
  components: {
    PropItem,
    TagBar,
    FloatLayer,
  },
  data() {
    return {
      tags: [
        {
          name: "ALL",
          title: "全部",
          count: 0,
          own: 0,
        },
        {
          name: "U",
          title: "奥特曼",
          count: 0,
          own: 0,
        },
        {
          name: "K",
          title: "怪兽",
          count: 0,
          own: 0,
        },
        {
          name: "O",
          title: "其它",
          count: 0,
          own: 0,
        },
      ],
      nowList: null, //展示列表
      nowDetail: null,
      layerShow: false,
      collectStatus: false, //标记模式
      collectFilter: false, //过滤已拥有的
      collectList: [], //收藏列表
      shfiguarts: [
        {
          id: "F-1", //唯一ID
          type: "U", //U 奥特曼  M 怪兽  O 其它
          tag: ["U"], //标签：U 奥特曼  K 怪兽  O 其它
          name: "奥特曼", //名称
          link: [0], //关联奥特曼或怪兽实体数组
          color: null, //自定义颜色
          date: "2016.7.23", //首次发售日期
          way: null, //获取途径
          pic: "F-1.jpg",
        },
        {
          id: "F-2",
          type: "U",
          tag: ["U"],
          name: "奧特曼 50周年纪念版",
          link: [82],
          color: null,
          date: "2016.7.23",
          way: null,
          pic: "F-2.jpg",
        },
        {
          id: "F-3",
          type: "M",
          tag: ["K"],
          name: "巴尔坦星人",
          link: [82],
          color: null,
          date: "2016.8.11",
          way: null,
          pic: "F-3.jpg",
        },
        {
          id: "F-4",
          type: "M",
          tag: ["K"],
          name: "宇宙恐龙杰顿",
          link: [82],
          color: null,
          date: "2016.10.27",
          way: null,
          pic: "F-4.jpg",
        },
        {
          id: "F-5",
          type: "U",
          tag: ["U"],
          name: "佐菲",
          link: [82],
          color: null,
          date: "2016.11.19",
          way: null,
          pic: "F-5.jpg",
        },
        {
          id: "F-6",
          type: "U",
          tag: ["U"],
          name: "奥特曼（A型）",
          link: [82],
          color: null,
          date: "2017.9.30",
          way: null,
          pic: "F-6.jpg",
        },
        {
          id: "F-7",
          type: "U",
          tag: ["U"],
          name: "赛文奥特曼",
          link: [82],
          color: null,
          date: "2017.3.31",
          way: null,
          pic: "F-7.jpg",
        },
        {
          id: "F-8",
          type: "M",
          tag: ["K"],
          name: "巴尔坦星人 分身体",
          link: [82],
          color: null,
          date: "2017.4",
          way: null,
          pic: "F-8.jpg",
        },
        {
          id: "F-9",
          type: "M",
          tag: ["K"],
          name: "梅特龙星人",
          link: [82],
          color: null,
          date: "2017.4.29",
          way: null,
          pic: "F-9.jpg",
        },
        {
          id: "F-10",
          type: "M",
          tag: ["K"],
          name: "美菲拉斯星人",
          link: [82],
          color: null,
          date: "2017.5",
          way: null,
          pic: "F-10.jpg",
        },
        {
          id: "F-11",
          type: "M",
          tag: ["K"],
          name: "金古桥",
          link: [82],
          color: null,
          date: "2017.6.24",
          way: null,
          pic: "F-11.jpg",
        },
        {
          id: "F-12",
          type: "M",
          tag: ["K"],
          name: "哥莫拉",
          link: [82],
          color: null,
          date: "2017.7.21",
          way: null,
          pic: "F-12.jpg",
        },
        {
          id: "F-13",
          type: "U",
          tag: ["U"],
          name: "欧布奥特曼 欧布起源&原生之初",
          link: [82],
          color: null,
          date: "2017.8.11",
          way: null,
          pic: "F-13.jpg",
        },
        {
          id: "F-14",
          type: "U",
          tag: ["U"],
          name: "欧布奥特曼 原生之初",
          link: [82],
          color: null,
          date: "2017.8",
          way: null,
          pic: "F-14.jpg",
        },
        {
          id: "F-15",
          type: "M",
          tag: ["K"],
          name: "三面怪人达达",
          link: [82],
          color: null,
          date: "2017.11",
          way: null,
          pic: "F-15.jpg",
        },
        {
          id: "F-16",
          type: "U",
          tag: ["U"],
          name: "欧布奥特曼 重光形态",
          link: [82],
          color: null,
          date: "2017.12.29",
          way: null,
          pic: "F-16.jpg",
        },
        {
          id: "F-17",
          type: "M",
          tag: ["K"],
          name: "无限魔人伽古拉斯.伽古拉",
          link: [82],
          color: null,
          date: "2018.1",
          way: null,
          pic: "F-17.jpg",
        },
        {
          id: "F-18",
          type: "U",
          tag: ["U"],
          name: "捷德奥特曼 原始形态",
          link: [82],
          color: null,
          date: "2018.2.24",
          way: null,
          pic: "F-18.jpg",
        },
        {
          id: "F-19",
          type: "M",
          tag: ["K"],
          name: "嘎次星人",
          link: [82],
          color: null,
          date: "2018.3.31",
          way: null,
          pic: "F-19.jpg",
        },
        {
          id: "F-20",
          type: "U",
          tag: ["U"],
          name: "杰克奥特曼",
          link: [82],
          color: null,
          date: "2018.4.27",
          way: null,
          pic: "F-20.jpg",
        },
        {
          id: "F-21",
          type: "U",
          tag: ["K"],
          name: "扎拉布星人",
          link: [82],
          color: null,
          date: "2018.4",
          way: null,
          pic: "F-21.jpg",
        },
        {
          id: "F-22",
          type: "U",
          tag: ["U"],
          name: "欧布奥特曼 暗耀形态",
          link: [82],
          color: null,
          date: "2018.5",
          way: null,
          pic: "F-22.jpg",
        },
        {
          id: "F-23",
          type: "U",
          tag: ["K"],
          name: "双尾怪",
          link: [82],
          color: null,
          date: "2018.6.23",
          way: null,
          pic: "F-23.jpg",
        },
        {
          id: "F-24",
          type: "U",
          tag: ["K"],
          name: "极恶贝利亚",
          link: [82],
          color: null,
          date: "2018.6",
          way: null,
          pic: "F-24.jpg",
        },
        {
          id: "F-25",
          type: "U",
          tag: ["U"],
          name: "捷德奥特曼 尊皇形态",
          link: [82],
          color: null,
          date: "2018.7",
          way: null,
          pic: "F-25.jpg",
        },
        {
          id: "F-26",
          type: "U",
          tag: ["K"],
          name: "庞墩",
          link: [82],
          color: null,
          date: "2018.8",
          way: null,
          pic: "F-26.jpg",
        },
        {
          id: "F-27",
          type: "U",
          tag: ["K"],
          name: "磁力怪兽安东拉",
          link: [82],
          color: null,
          date: "2018.9",
          way: null,
          pic: "F-27.jpg",
        },
        {
          id: "F-28",
          type: "U",
          tag: ["U"],
          name: "艾克斯奥特曼&哥莫拉装甲",
          link: [82],
          color: null,
          date: "2018.10.27",
          way: null,
          pic: "F-28.jpg",
        },
        {
          id: "F-29",
          type: "U",
          tag: ["K"],
          name: "暗黑欧布奥特曼",
          link: [82],
          color: null,
          date: "2018.10",
          way: null,
          pic: "F-29.jpg",
        },
        {
          id: "F-30",
          type: "U",
          tag: ["U"],
          name: "赛罗奥特曼 超越形态",
          link: [82],
          color: null,
          date: "2018.11",
          way: null,
          pic: "F-30.jpg",
        },
        {
          id: "F-31",
          type: "U",
          tag: ["K"],
          name: "古墩",
          link: [82],
          color: null,
          date: "2018.12",
          way: null,
          pic: "F-31.jpg",
        },
        {
          id: "F-32",
          type: "U",
          tag: ["U"],
          name: "罗索奥特曼 烈火形态",
          link: [82],
          color: null,
          date: "2018.12.15",
          way: null,
          pic: "F-32.jpg",
        },
        {
          id: "F-33",
          type: "U",
          tag: ["U"],
          name: "布鲁奥特曼 跃水形态",
          link: [82],
          color: null,
          date: "2018.12.15",
          way: null,
          pic: "F-33.jpg",
        },
        {
          id: "F-34",
          type: "U",
          tag: ["U"],
          name: "罗索奥特曼 旋风形态",
          link: [82],
          color: null,
          date: "2019.1.19",
          way: null,
          pic: "F-34.jpg",
        },
        {
          id: "F-35",
          type: "U",
          tag: ["U"],
          name: "布鲁奥特曼 大地形态",
          link: [82],
          color: null,
          date: "2019.1.19",
          way: null,
          pic: "F-35.jpg",
        },
        {
          id: "F-36",
          type: "U",
          tag: ["U"],
          name: "赛罗奥特曼",
          link: [82],
          color: null,
          date: "2019.2.16",
          way: null,
          pic: "F-36.jpg",
        },
        {
          id: "F-37",
          type: "U",
          tag: ["K"],
          name: "贝利亚奥特曼",
          link: [82],
          color: null,
          date: "2019.4.27",
          way: null,
          pic: "F-37.jpg",
        },
        {
          id: "F-38",
          type: "U",
          tag: ["U"],
          name: "罗索奥特曼 大地形态",
          link: [82],
          color: null,
          date: "2019.5",
          way: null,
          pic: "F-38.jpg",
        },
        {
          id: "F-39",
          type: "U",
          tag: ["U"],
          name: "布鲁奥特曼 旋风形态",
          link: [82],
          color: null,
          date: "2019.5",
          way: null,
          pic: "F-39.jpg",
        },
        {
          id: "F-40",
          type: "U",
          tag: ["U"],
          name: "罗布奥特曼",
          link: [82],
          color: null,
          date: "2019.6",
          way: null,
          pic: "F-40.jpg",
        },
        {
          id: "F-41",
          type: "U",
          tag: ["U"],
          name: "维克特利奥特曼",
          link: [82],
          color: null,
          date: "2019.6.15",
          way: null,
          pic: "F-41.jpg",
        },
        {
          id: "F-42",
          type: "U",
          tag: ["K"],
          name: "布莱克王",
          link: [82],
          color: null,
          date: "2019.7",
          way: null,
          pic: "F-42.jpg",
        },
        {
          id: "F-43",
          type: "U",
          tag: ["U"],
          name: "捷德奥特曼 豪勇形态",
          link: [82],
          color: null,
          date: "2019.8",
          way: null,
          pic: "F-43.jpg",
        },
        {
          id: "F-44",
          type: "U",
          tag: ["U"],
          name: "捷德奥特曼 原始形态 会场限定版",
          link: [82],
          color: null,
          date: "2019.3",
          way: null,
          pic: "F-44.jpg",
        },
        {
          id: "F-45",
          type: "U",
          tag: ["K"],
          name: "无幻魔人伽古拉斯.伽古拉 会场限定版",
          link: [82],
          color: null,
          date: "2019.3",
          way: null,
          pic: "F-45.jpg",
        },
        {
          id: "F-46",
          type: "U",
          tag: ["U"],
          name: "银河奥特曼",
          link: [82],
          color: null,
          date: "2019.10.19",
          way: null,
          pic: "F-46.jpg",
        },
        {
          id: "F-47",
          type: "U",
          tag: ["U"],
          name: "泰罗奥特曼",
          link: [82],
          color: null,
          date: "2019.11.30",
          way: null,
          pic: "F-47.jpg",
        },
        {
          id: "F-48",
          type: "U",
          tag: ["U"],
          name: "泰迦奥特曼",
          link: [82],
          color: null,
          date: "2019.12.14",
          way: null,
          pic: "F-48.jpg",
        },
        {
          id: "F-49",
          type: "U",
          tag: ["U"],
          name: "强壮日冕＆月神奇迹形态 赛罗奥特曼",
          link: [82],
          color: null,
          date: "2019.10.25",
          way: null,
          pic: "F-49.jpg",
        },
        {
          id: "F-50",
          type: "U",
          tag: ["K"],
          name: "黑暗捷德奥特曼",
          link: [82],
          color: null,
          date: "2020.3",
          way: null,
          pic: "F-50.jpg",
        },
        {
          id: "F-51",
          type: "U",
          tag: ["K"],
          name: "黑暗艾克斯奥特曼＆哥莫拉装甲",
          link: [82],
          color: null,
          date: "2020.4",
          way: null,
          pic: "F-51.jpg",
        },
        {
          id: "F-52",
          type: "U",
          tag: ["K"],
          name: "托雷基亚奥特曼",
          gallery: 8,
          link: [82],
          color: null,
          date: "2020.6",
          way: null,
          pic: "F-52.jpg",
        },
        {
          id: "F-53",
          type: "U",
          tag: ["U"],
          name: "泰迦奥特曼 三重斯特利姆形态",
          gallery: 6,
          link: [82],
          color: null,
          date: "2020.6",
          way: null,
          pic: "F-53.jpg",
        },
        {
          id: "F-54",
          type: "U",
          tag: ["U"],
          name: "奥特曼[BEST SELECTION]",
          gallery: 6,
          link: [82],
          color: null,
          date: "2020.6.13",
          way: null,
          pic: "F-54.jpg",
        },
        {
          id: "F-55",
          type: "U",
          tag: ["U"],
          name: "艾斯奥特曼",
          gallery: 6,
          link: [82],
          color: null,
          date: "2020.7.18",
          way: null,
          pic: "F-55.jpg",
        },
        {
          id: "F-56",
          type: "U",
          tag: ["U"],
          name: "捷德奥特曼 究极最终形态",
          gallery: 6,
          link: [82],
          color: null,
          date: "2020.7",
          way: null,
          pic: "F-56.jpg",
        },
        {
          id: "F-57",
          type: "U",
          tag: ["U"],
          name: "泰塔斯奥特曼",
          gallery: 7,
          link: [82],
          color: null,
          date: "2020.9",
          way: null,
          pic: "F-57.jpg",
        },
        {
          id: "F-58",
          type: "U",
          tag: ["U"],
          name: "赛罗奥特曼 光辉形态",
          gallery: 7,
          link: [82],
          color: null,
          date: "2020.10",
          way: null,
          pic: "F-58.jpg",
        },
        {
          id: "F-59",
          type: "U",
          tag: ["U"],
          name: "泽塔奥特曼 阿尔法装甲",
          gallery: 6,
          link: [82],
          color: null,
          date: "2020.12.19",
          way: null,
          pic: "F-59.jpg",
        },
        {
          id: "F-60",
          type: "U",
          tag: ["U"],
          name: "捷德奥特曼 原始形态(NEW GENERATION版)",
          gallery: 10,
          link: [82],
          color: null,
          date: "2020.12.19",
          way: null,
          pic: "F-60.jpg",
        },
        {
          id: "F-61",
          type: "U",
          tag: ["U"],
          name: "银河奥特曼(斯特利姆形态)",
          gallery: 7,
          link: [82],
          color: null,
          date: "2021.1",
          way: null,
          pic: "F-61.jpg",
        },
        {
          id: "F-62",
          type: "U",
          tag: ["U"],
          name: "赛罗奥特曼(银河光辉无限形态)",
          gallery: 5,
          link: [82],
          color: null,
          date: "2021.1",
          way: null,
          pic: "F-62.jpg",
        },
        {
          id: "F-63",
          type: "U",
          tag: ["U"],
          name: "赛罗奥特曼 十周年特别配色ver.",
          gallery: 7,
          link: [82],
          color: null,
          date: "2021.4",
          way: null,
          pic: "F-63.jpg",
        },
        {
          id: "F-64",
          type: "U",
          tag: ["U"],
          name: "风马奥特曼",
          gallery: 6,
          link: [82],
          color: null,
          date: "2021.2",
          way: null,
          pic: "F-64.jpg",
        },
        {
          id: "F-65",
          type: "U",
          tag: ["K"],
          name: "特空机1号 赛文加",
          gallery: 9,
          link: [82],
          color: null,
          date: "2021.6",
          way: null,
          pic: "F-65.jpg",
        },
        {
          id: "F-66",
          type: "U",
          tag: ["U"],
          name: "泰迦奥特曼 Special Clear Color Ver.",
          gallery: 6,
          link: [82],
          color: null,
          date: "2020.12",
          way: null,
          pic: "F-66.jpg",
        },
        {
          id: "F-67",
          type: "U",
          tag: ["K"],
          name: "杰顿 一兆度火球ver.",
          gallery: 6,
          link: [82],
          color: null,
          date: "2021.4",
          way: null,
          pic: "F-67.jpg",
        },
        {
          id: "F-68",
          type: "U",
          tag: ["K"],
          name: "伽古拉斯.伽古拉（新生代版）",
          gallery: 9,
          link: [82],
          color: null,
          date: "2021.5",
          way: null,
          pic: "F-68.jpg",
        },
        {
          id: "F-69",
          type: "U",
          tag: ["U"],
          name: "新·奥特曼",
          gallery: 8,
          link: [82],
          color: null,
          date: "2021.6.26",
          way: null,
          pic: "F-69.jpg",
        },
        {
          id: "F-70",
          type: "U",
          tag: ["U"],
          name: "捷德奥特曼 银河初升形态",
          gallery: 8,
          link: [82],
          color: null,
          date: "2021.7",
          way: null,
          pic: "F-70.jpg",
        },
        {
          id: "F-71",
          type: "U",
          tag: ["U"],
          name: "泽塔奥特曼 伽玛未来",
          gallery: 8,
          link: [82],
          color: null,
          date: "2021.9",
          way: null,
          pic: "F-71.jpg",
        },
        {
          id: "F-72",
          type: "U",
          tag: ["U"],
          name: "泽塔奥特曼 原生形态",
          gallery: 9,
          link: [82],
          color: null,
          date: "2021.9.18",
          way: null,
          pic: "F-72.jpg",
        },
        {
          id: "F-73",
          type: "U",
          tag: ["U"],
          name: "雷欧奥特曼",
          gallery: 7,
          link: [82],
          color: null,
          date: "2021.11",
          way: null,
          pic: "F-73.jpg",
        },
        {
          id: "F-74",
          type: "U",
          tag: ["U"],
          name: "奥特曼 55周年纪念Ver.",
          gallery: 9,
          link: [82],
          color: null,
          date: "2021.11",
          way: null,
          pic: "F-74.jpg",
        },
        {
          id: "F-75",
          type: "U",
          tag: ["U"],
          name: "特利迦奥特曼 复合形态",
          gallery: 8,
          link: [82],
          color: null,
          date: "2021.11",
          way: null,
          pic: "F-75.jpg",
        },
        {
          id: "F-76",
          type: "U",
          tag: ["U"],
          name: "终极赛罗 闪耀型",
          gallery: 10,
          link: [82],
          color: null,
          date: "2021.12",
          way: null,
          pic: "F-76.jpg",
        },
        {
          id: "F-77",
          type: "U",
          tag: ["U"],
          name: "迪迦奥特曼 复合型",
          gallery: 10,
          link: [82],
          color: null,
          date: "2021.7.31",
          way: null,
          pic: "F-77.jpg",
        },
        {
          id: "F-78",
          type: "U",
          tag: ["U"],
          name: "泽塔奥特曼 阿尔法装甲特别配色版",
          gallery: 8,
          link: [82],
          color: null,
          date: "2021.11",
          way: null,
          pic: "F-78.jpg",
        },
        {
          id: "F-79",
          type: "M",
          tag: ["K"],
          name: "超古代怪兽 哥尔赞",
          gallery: 6,
          link: null,
          color: null,
          date: "2022.1",
          way: null,
          pic: "F-79.jpg",
        },
        {
          id: "F-80",
          type: "U",
          tag: ["O"],
          name: "GUTS胜利飞燕1号&2号",
          gallery: 9,
          link: null,
          color: null,
          date: "2022.1",
          way: null,
          pic: "F-80.jpg",
        },
        {
          id: "F-81",
          type: "U",
          tag: ["K"],
          name: "特空机3号 金古桥军械库定制",
          gallery: 7,
          link: null,
          color: null,
          date: "2022.3",
          way: null,
          pic: "F-81.jpg",
        },
        {
          id: "F-82",
          type: "U",
          tag: ["U"],
          name: "泽塔奥特曼 德尔塔天爪",
          gallery: 10,
          link: null,
          color: null,
          date: "2022.1",
          way: null,
          pic: "F-82.jpg",
        },
        {
          id: "F-83",
          type: "U",
          tag: ["U"],
          name: "泰迦奥特曼 彩虹三重斯特利姆形态",
          gallery: 7,
          link: null,
          color: null,
          date: "2022.2",
          way: null,
          pic: "F-83.jpg",
        },
        {
          id: "F-84",
          type: "U",
          tag: ["U"],
          name: "泽塔奥特曼 贝塔冲击",
          gallery: 8,
          link: null,
          color: null,
          date: "2022.4",
          way: null,
          pic: "F-84.jpg",
        },
        {
          id: "F-85",
          type: "U",
          tag: ["U"],
          name: "利布特奥特曼",
          gallery: 8,
          link: null,
          color: null,
          date: "2022.4",
          way: null,
          pic: "F-85.jpg",
        },
        {
          id: "F-86",
          type: "M",
          tag: ["K"],
          name: "基里艾洛德人",
          gallery: 7,
          link: "https://tamashii.jp/item/13867/",
          color: null,
          date: "2022.5",
          way: null,
          pic: "F-86.jpg",
        },
        {
          id: "F-87",
          type: "U",
          tag: ["U"],
          name: "风马奥特曼 Special Clear Color Ver.",
          gallery: 7,
          link: [80],
          color: null,
          date: "2021.12",
          way: null,
          pic: "F-87.jpg",
        },
        {
          id: "F-88",
          type: "U",
          tag: ["U"],
          name: "迪迦奥特曼 强力型",
          gallery: 8,
          link: [80],
          color: null,
          date: "2022.5",
          way: null,
          pic: "F-88.jpg",
        },
        {
          id: "F-89",
          type: "U",
          tag: ["U"],
          name: "黑暗特利迦",
          gallery: 8,
          link: null,
          color: null,
          date: "2022.6",
          way: null,
          pic: "F-89.jpg",
        },
        {
          id: "F-90",
          type: "U",
          tag: ["U"],
          name: "特利迦奥特曼 空中型",
          gallery: 8,
          link: null,
          color: null,
          date: "2022.7",
          way: null,
          pic: "F-90.jpg",
        },
        {
          id: "F-91",
          type: "U",
          tag: ["U"],
          name: "妖丽战士 卡尔蜜拉",
          gallery: 8,
          link: null,
          color: null,
          date: "2022.8",
          way: null,
          pic: "F-91.jpg",
        },
        {
          id: "F-92",
          type: "U",
          tag: ["U"],
          name: "初代奥特曼 真骨雕",
          gallery: 9,
          link: null,
          color: null,
          date: "2022.7",
          way: null,
          pic: "F-92.jpg",
        },
        {
          id: "F-93",
          type: "U",
          tag: ["U"],
          name: "格力乔奥特曼",
          gallery: 10,
          link: null,
          color: null,
          date: "2022.9",
          way: null,
          pic: "F-93.jpg",
        },
        {
          id: "F-94",
          type: "U",
          tag: ["U"],
          name: "特空机1号 宇宙赛文加",
          gallery: 7,
          link: null,
          color: null,
          date: "2022.12",
          way: null,
          pic: "F-94.jpg",
        },
        {
          id: "F-95",
          type: "U",
          tag: ["U"],
          name: "阿斯特拉",
          gallery: 7,
          link: null,
          color: null,
          date: "2022.10",
          way: null,
          pic: "F-95.jpg",
        },
      ],
    };
  },
  methods: {
    getDataByTag(tag) {
      if (tag == "ALL") {
        this.nowList = this.shfiguarts;
      } else {
        this.nowList = this.getListByTag(tag);
      }
    },
    // 根据tag标签获取数据
    getListByTag(tag) {
      let arr = [];
      this.shfiguarts.forEach((item, index, array) => {
        if (item.tag.indexOf(tag) != -1) {
          arr.push(item);
        }
      });
      return arr;
    },
    // 根据collectStatus状态,进行收藏模式与详情模式切换
    showDetail(item) {
      if (this.collectStatus) {
        // 收藏模式
        if (this.collectList.indexOf(item.id) == -1) {
          this.collectList.push(item.id); //新增项
        } else {
          this.collectList.splice(this.collectList.indexOf(item.id), 1); //删除项
        }
        this.$Tools.$setStroage("shf", this.collectList); //保存最新数据
        this.getCollectProgress();
      } else {
        // 详情模式
        this.layerShow = true;
        this.nowDetail = item;
      }
    },
    // 隐藏详情
    hideDetail(visible) {
      this.layerShow = visible;
    },
    // 加载收藏数据
    getCollectData() {
      this.collectList =
        this.$Tools.$getStroage("shf") != null
          ? this.$Tools.$getStroage("shf")
          : [];
    },
    // 切换收藏状态
    collectToggle() {
      this.collectStatus = this.collectStatus ? false : true;
    },
    // 获取拥有状态
    getCollect(id) {
      return this.collectList.indexOf(id) != -1; //返回true为已标记
    },
    //过滤已拥有的
    getCollectFilter() {
      this.collectFilter = this.collectFilter ? false : true;
    },
    // 获取收藏进程
    // 表示有 !=-1
    getCollectProgress() {
      this.tags.forEach((i, num, arr) => {
        this.tags[num].count = 0;
        this.tags[num].own = 0;
      });
      this.tags[0].count = this.shfiguarts.length;
      this.tags[0].own = this.collectList.length;
      this.shfiguarts.forEach((item, index, array) => {
        this.tags.forEach((i, num, arr) => {
          //获得总数
          if (item.tag[0].indexOf(i.name) != -1) {
            this.tags[num].count = this.tags[num].count + 1;
          }
          //获得已拥有数
          if (
            this.collectList.indexOf(item.id) != -1 &&
            this.tags[num].name == item.tag[0]
          ) {
            this.tags[num].own = this.tags[num].own + 1;
          }
        });
      });
    },
  },
  created() {
    this.nowList = this.shfiguarts.reverse();
    this.getCollectData();
    this.getCollectProgress();
  },
};
</script>

<style scoped></style>
