<template>
  <div class="item-list" :class="collectStatus ? 'collect-status' : ''">
    <floatLayer
      :show="layerShow"
      :item="nowDetail"
      :urlType="2"
      @parentEvent="hideDetail"
    />
    <div class="ctrl-panel">
      <div
        class="switch-box"
        :class="collectFilter ? 'active' : ''"
        @click="getCollectFilter"
      >
        <div class="switch-label">过滤已拥有的</div>
        <div class="switch-btn"></div>
      </div>
      <div
        class="btn"
        v-text="collectStatus ? '退出标记模式' : '标记我已拥有的'"
        @click="collectToggle"
      ></div>
      <tagBar v-bind:tags="tags" @parentEvent="getDataByTag" />
    </div>
    <propItem
      v-for="hk in nowList"
      v-bind:item="hk"
      :class="getCollect(hk.id) ? 'collect' : ''"
      :urlType="2"
      :showPic="true"
      :key="hk.id"
      :defaultColor="'#5420ae'"
      :barColor="hk.color"
      @click.native="showDetail(hk)"
      v-show="collectFilter == false || !getCollect(hk.id)"
    />
  </div>
</template>

<script>
import PropItem from "@/components/PropItem";
import TagBar from "@/components/TagBar";
import FloatLayer from "@/components/FloatLayer";
export default {
  name: "Sofubi",
  components: {
    PropItem,
    TagBar,
    FloatLayer,
  },
  data() {
    return {
      tags: [
        {
          name: "ALL",
          title: "全部",
        },
        {
          name: "S",
          title: "奥特曼",
        },
        {
          name: "EX",
          title: "奥特限定",
        },
        {
          name: "K",
          title: "怪兽",
        },
        {
          name: "EX-K",
          title: "怪兽限定",
        }
      ],
      nowList: null, //展示列表
      nowDetail: null,
      layerShow: false,
      collectStatus: false, //标记模式
      collectFilter: false, //过滤已拥有的
      collectList: [], //收藏列表
      sofubi500: [
        {
          id: "S-01", //唯一ID
          type: "U", //U 奥特曼  M 怪兽  O 其它
          tag: ["S"], //标签：S 奥特曼 EX 奥特限定  K 怪兽 EX-K 限定怪兽
          name: "奥特曼", //名称
          link: [0], //关联奥特曼或怪兽实体数组
          color: "#F44336", //自定义颜色
        },
        {
          id: "S-02",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-03",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-04",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-05",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-06",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-07",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-08",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-09",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-10",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-11",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-12",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-13",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-14",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-15",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-16",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-17",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-18",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-19",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-20",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-21",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-22",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-23",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-24",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-25",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-26",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-27",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-28",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-29",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-30",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-31",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-32",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-33",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-34",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-35",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-36",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-37",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-38",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-39",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-40",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-41",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-42",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-43",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-44",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-45",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-46",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-47",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-48",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-49",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-50",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-51",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-52",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-53",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-54",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-55",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-56",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-57",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-58",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-59",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-60",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-61",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-62",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-63",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-64",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-65",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-66",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-67",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-68",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-69",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-70",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-71",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-72",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-73",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-74",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-75",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-76",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-77",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-78",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-79",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-80",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-81",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "S-82",
          type: "U",
          tag: ["S"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-01",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-02",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-03",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-04",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-05",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-06",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-07",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-08",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-09",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-10",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-11",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-12",
          type: "U",
          tag: ["EX"],
          name: "奥特曼",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-01",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-02",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-03",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-04",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-05",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-06",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-07",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-08",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-09",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-10",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-11",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-12",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-13",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-14",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-15",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-16",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-17",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-18",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-19",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-20",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-21",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-22",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-23",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-24",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-25",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-26",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-27",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-28",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-29",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-30",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-31",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-32",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-33",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-34",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-35",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-36",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-37",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-38",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-39",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-40",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-41",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-42",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-43",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-44",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-45",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-46",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-47",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-48",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-49",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-50",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-51",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-52",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-53",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-54",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-55",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-56",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-57",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-58",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-59",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-60",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-61",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-62",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-63",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-64",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-65",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-66",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-67",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-68",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-69",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-70",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-71",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-72",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-73",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-74",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-75",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-76",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-77",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-78",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-79",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-80",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-81",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-82",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-83",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-84",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-85",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-86",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-87",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-88",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-89",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-90",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-91",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-92",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-93",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-94",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-95",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-96",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-97",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-98",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-99",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-100",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-101",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-102",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-103",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-104",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-105",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-106",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-107",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-108",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-109",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-110",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-111",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-112",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-113",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-114",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-115",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-116",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-117",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-118",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-119",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-120",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-121",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-122",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-123",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-124",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-125",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-126",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-127",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-128",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-129",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-130",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-131",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-132",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-133",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-134",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-135",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-136",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-137",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-138",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-139",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-140",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-141",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-142",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-143",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-144",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-145",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-146",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-147",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-148",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-149",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-150",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-151",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "K-152",
          type: "M",
          tag: ["K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-K-01",
          type: "M",
          tag: ["EX-K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-K-02",
          type: "M",
          tag: ["EX-K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-K-03",
          type: "M",
          tag: ["EX-K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        },
        {
          id: "EX-K-04",
          type: "M",
          tag: ["EX-K"],
          name: "怪兽",
          link: [0],
          color: "#F44336",
        }
      ],
    };
  },
  methods: {
    getDataByTag(tag) {
      if (tag == "ALL") {
        this.nowList = this.sofubi500;
      } else {
        this.nowList = this.getListByTag(tag);
      }
    },
    // 根据tag标签获取数据
    getListByTag(tag) {
      let arr = [];
      this.sofubi500.forEach((item, index, array) => {
        if (item.tag.indexOf(tag) != -1) {
          arr.push(item);
        }
      });
      return arr;
    },
    // 根据collectStatus状态,进行收藏模式与详情模式切换
    showDetail(item) {
      if (this.collectStatus) {
        // 收藏模式
        if (this.collectList.indexOf(item.id) == -1) {
          this.collectList.push(item.id); //新增项
        } else {
          this.collectList.splice(this.collectList.indexOf(item.id), 1); //删除项
        }
        this.$Tools.$setStroage("sofubi500", this.collectList); //保存最新数据
      } else {
        // 详情模式
        this.layerShow = true;
        this.nowDetail = item;
      }
    },
    // 隐藏详情
    hideDetail(visible) {
      this.layerShow = visible;
    },
    // 加载收藏数据
    getCollectData() {
      this.collectList =
        this.$Tools.$getStroage("sofubi500") != null
          ? this.$Tools.$getStroage("sofubi500")
          : [];
    },
    // 切换收藏状态
    collectToggle() {
      this.collectStatus = this.collectStatus ? false : true;
    },
    // 获取拥有状态
    getCollect(id) {
      return this.collectList.indexOf(id) != -1; //返回true为已标记
    },
    //过滤已拥有的
    getCollectFilter() {
      this.collectFilter = this.collectFilter ? false : true;
    },
    // 获取收藏进程
    getCollectProgress() {},
  },
  created() {
    this.nowList = this.sofubi500;
    this.getCollectData();
  },
};
</script>

<style scoped>
</style>
